### ISSUE TITLE
Error "unknown resource: null_resource" during validation

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [GoogleCloudPlatform/terraform-validator#210]
## Description

When running a validate I receive an error:

```
› terraform-validator validate --policy-path=./ plan.json
ERROR: logging before flag.Parse: I0330 10:36:32.100165   24752 convert.go:183] unknown resource: null_resource
Error: validating: FCV: initializing gcv validator: failed to read files from lib: failed to read files in lib: error visiting path lib: lstat lib: no such file or directory
```

The Terraform code does not contain valid GCP resources but instead a null_resource for testing. I would have expected it to ignore this resource and either accept or reject the code based on the policy but I'm getting the error instead.

The directory structure is like so during local testing:

```
.
├── main.tf
├── plan.json
├── plan.tfplan
├── policies
│   └── constraints
│       └── allowed_resources_types.yaml
├── values
│   └── dummy.tfvars
└── variables.tf

3 directories, 6 files

```

Using a `GCPAllowedResourceTypesConstraintV2` policy like:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPAllowedResourceTypesConstraintV2
metadata:
  name: allow_only_folders
  annotations:
    description: Restricts anything other than folders in the folders layer of the organisation repository
spec:
  severity: high
  parameters:
    mode: "allowlist"
    resource_type_list:
    - cloudresourcemanager.googleapis.com/Folders

```
