### ISSUE TITLE
Validator Not Returning resource.data.zone

### ISSUE THREAD

**Issue by jdyke** [GoogleCloudPlatform/terraform-validator#54]
Related to https://github.com/forseti-security/policy-library/issues/121

validator is not returning the zone when parsing compute instances. 

Template: gcp_compute_zone_v1.yaml

Constraint:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeZoneConstraintV1
metadata:
  name: compute_zone_denylist_one
spec:
  severity: high
  match:
    target: ["organization/*"]
  parameters:
    mode: "denylist"
    zones:
      - asia-east1-b
```

tf code:

```
variable project {}

provider "google" {
  project = "${var.project}"
  region = "asia-east1"
}

resource "google_compute_instance" "common" {
    name         = "test-instance"
    machine_type = "n1-standard-1"
    zone = "asia-east1-b"

    boot_disk {
      initialize_params {
        image = "debian-cloud/debian-9"
      }
    }

    network_interface {
      network = "default"
    }
}
```
